<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<UseMaui>true</UseMaui>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' == 'Unix'">
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' != 'Unix'">
		<TargetFrameworks>net10.0;net10.0-ios;net10.0-maccatalyst;net10.0-android</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="7.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.30" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.30" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ChronoWiz.Shared\ChronoWiz.Shared.csproj" />
	</ItemGroup>
</Project>
